name:                aoc
version:             0.1.0.0
github:              "githubuser/aoc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

_exe-defs: &exe-defaults
  source-dirs:    app
  dependencies:   [aoc]
  other-modules:  []
  ghc-options:    [-threaded, -rtsopts, -with-rtsopts=-N]

executables:
  aoc-exe:
    <<: *exe-defaults
    main:                Main.hs
  d1:
    <<: *exe-defaults
    main:                Day01.hs
  d2:
    <<: *exe-defaults
    main:                Day02.hs
  d3:
    <<: *exe-defaults
    main:                Day03.hs
  d4:
    <<: *exe-defaults
    main:                Day04.hs
  d5:
    <<: *exe-defaults
    main:                Day05.hs
  d6:
    <<: *exe-defaults
    main:                Day06.hs
  d7:
    <<: *exe-defaults
    main:                Day07.hs


tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
